In [51]:
from scipy.io import mmread
import pandas as pd
import scanpy as sc
import anndata

In [9]:
! mkdir -p ../../../Data/Revision/CRC_Outcome
! mkdir -p ../../../Data/Revision/CRC_Outcome/Idvfiles

In [7]:
! wget -P ../../../Data/Revision/CRC_Outcome/ https://ftp.ncbi.nlm.nih.gov/geo/series/GSE205nnn/GSE205506/suppl/GSE205506_RAW.tar

--2024-10-27 22:05:21--  https://ftp.ncbi.nlm.nih.gov/geo/series/GSE205nnn/GSE205506/suppl/GSE205506_RAW.tar
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.13, 130.14.250.31, 130.14.250.7, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1585182720 (1.5G) [application/x-tar]
Saving to: ‘../../../Data/Revision/CRC_Outcome/GSE205506_RAW.tar.1’

 2% [>                                      ] 43,589,632  7.13MB/s  eta 3m 33s ^C

In [79]:
! wget https://www.cell.com/cms/10.1016/j.ccell.2023.04.011/attachment/c9110253-41ec-458a-bc9d-c6be5e3f9b21/mmc2.xlsx

--2024-10-28 21:33:30--  https://www.cell.com/cms/10.1016/j.ccell.2023.04.011/attachment/c9110253-41ec-458a-bc9d-c6be5e3f9b21/mmc2.xlsx
Resolving www.cell.com (www.cell.com)... 172.66.0.112, 162.159.140.114
Connecting to www.cell.com (www.cell.com)|172.66.0.112|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-10-28 21:33:30 ERROR 403: Forbidden.

In [10]:
! tar -xf ../../../Data/Revision/CRC_Outcome/GSE205506_RAW.tar -C ../../../Data/Revision/CRC_Outcome/Idvfiles

In [65]:
sample_info = [['GSM6213956', '111', 'P11', 'colon', 'tumor', 'Anti-PD-1+celecoxib'],
['GSM6213957', '112', 'P11', 'colon', 'normal', 'Anti-PD-1+celecoxib'],
['GSM6213958', '121', 'P12', 'colon', 'tumor', 'anti-PD-1'],
['GSM6213959', '122', 'P12', 'colon', 'normal', 'anti-PD-1'],
['GSM6213960', '141', 'P14', 'colon', 'tumor', 'Anti-PD-1+celecoxib'],
['GSM6213961', '151', 'P15', 'colon', 'tumor', 'anti-PD-1'],
['GSM6213962', '152', 'P15', 'colon', 'normal', 'anti-PD-1'],
['GSM6213963', '171', 'P17', 'colon', 'tumor', 'anti-PD-1'],
['GSM6213964', '172', 'P17', 'colon', 'normal', 'anti-PD-1'],
['GSM6213965', '181', 'P18', 'colon', 'tumor', 'anti-PD-1'],
['GSM6213966', '182', 'P18', 'colon', 'normal', 'anti-PD-1'],
['GSM6213967', '191', 'P19', 'colon', 'tumor', 'Anti-PD-1+celecoxib'],
['GSM6213968', '192', 'P19', 'colon', 'normal', 'Anti-PD-1+celecoxib'],
['GSM6213969', '211', 'P21', 'rectum', 'tumor', 'Anti-PD-1+celecoxib'],
['GSM6213970', '213', 'P21', 'rectum', 'tumor', 'untreated'],
['GSM6213971', '233', 'P23', 'colon', 'tumor', 'untreated'],
['GSM6213972', '241', 'P24', 'colon', 'tumor', 'Anti-PD-1+celecoxib'],
['GSM6213973', '243', 'P24', 'colon', 'tumor', 'untreated'],
['GSM6213974', '251', 'P25', 'colon', 'tumor', 'Anti-PD-1+celecoxib'],
['GSM6213975', '252', 'P25', 'colon', 'normal', 'Anti-PD-1+celecoxib'],
['GSM6213976', '253', 'P25', 'colon', 'tumor', 'untreated'],
['GSM6213977', '261', 'P26', 'colon', 'tumor', 'Anti-PD-1+celecoxib'],
['GSM6213978', '271', 'P27', 'colon', 'tumor', 'anti-PD-1'],
['GSM6213979', '272', 'P27', 'colon', 'normal', 'anti-PD-1'],
['GSM6213980', '273', 'P27', 'colon', 'tumor', 'untreated'],
['GSM6213981', '281', 'P28', 'colon', 'tumor', 'anti-PD-1'],
['GSM6213982', '282', 'P28', 'colon', 'normal', 'anti-PD-1'],
['GSM6213983', '283', 'P28', 'colon', 'tumor', 'untreated'],
['GSM6213984', '291', 'P29', 'colon', 'tumor', 'anti-PD-1'],
['GSM6213985', '292', 'P29', 'colon', 'normal', 'anti-PD-1'],
['GSM6213986', '301', 'P30', 'colon', 'tumor', 'anti-PD-1'],
['GSM6213987', '302', 'P30', 'colon', 'normal', 'anti-PD-1'],
['GSM6213988', '303', 'P30', 'colon', 'tumor', 'untreated'],
['GSM6213989', '311', 'P31', 'colon', 'tumor', 'anti-PD-1'],
['GSM6213990', '312', 'P31', 'colon', 'normal', 'anti-PD-1'],
['GSM6213991', '313', 'P31', 'colon', 'tumor', 'untreated'],
['GSM6213992', '321', 'P32', 'colon', 'tumor', 'Anti-PD-1+celecoxib'],
['GSM6213993', '322', 'P32', 'colon', 'normal', 'Anti-PD-1+celecoxib'],
['GSM6213994', '323', 'P32', 'colon', 'tumor', 'untreated'],
['GSM6213995', '333', 'P33', 'rectum', 'tumor', 'untreated']]

sample_info = pd.DataFrame(sample_info, columns=['GSM', 'sample', 'Patient', 'Location', 'Type', 'Treatment'])
sample_info

           GSM sample Patient Location    Type            Treatment
0   GSM6213956    111     P11    colon   tumor  Anti-PD-1+celecoxib
1   GSM6213957    112     P11    colon  normal  Anti-PD-1+celecoxib
2   GSM6213958    121     P12    colon   tumor            anti-PD-1
3   GSM6213959    122     P12    colon  normal            anti-PD-1
4   GSM6213960    141     P14    colon   tumor  Anti-PD-1+celecoxib
5   GSM6213961    151     P15    colon   tumor            anti-PD-1
6   GSM6213962    152     P15    colon  normal            anti-PD-1
7   GSM6213963    171     P17    colon   tumor            anti-PD-1
8   GSM6213964    172     P17    colon  normal            anti-PD-1
9   GSM6213965    181     P18    colon   tumor            anti-PD-1
10  GSM6213966    182     P18    colon  normal            anti-PD-1
11  GSM6213967    191     P19    colon   tumor  Anti-PD-1+celecoxib
12  GSM6213968    192     P19    colon  normal  Anti-PD-1+celecoxib
13  GSM6213969    211     P21   rectum   tumor  Anti-PD-1+celecoxib
14  GSM6213970    213     P21   rectum   tumor            untreated
15  GSM6213971    233     P23    colon   tumor            untreated
16  GSM6213972    241     P24    colon   tumor  Anti-PD-1+celecoxib
17  GSM6213973    243     P24    colon   tumor            untreated
18  GSM6213974    251     P25    colon   tumor  Anti-PD-1+celecoxib
19  GSM6213975    252     P25    colon  normal  Anti-PD-1+celecoxib
20  GSM6213976    253     P25    colon   tumor            untreated
21  GSM6213977    261     P26    colon   tumor  Anti-PD-1+celecoxib
22  GSM6213978    271     P27    colon   tumor            anti-PD-1
23  GSM6213979    272     P27    colon  normal            anti-PD-1
24  GSM6213980    273     P27    colon   tumor            untreated
25  GSM6213981    281     P28    colon   tumor            anti-PD-1
26  GSM6213982    282     P28    colon  normal            anti-PD-1
27  GSM6213983    283     P28    colon   tumor            untreated
28  GSM6213984    291     P29    colon   tumor            anti-PD-1
29  GSM6213985    292     P29    colon  normal            anti-PD-1
30  GSM6213986    301     P30    colon   tumor            anti-PD-1
31  GSM6213987    302     P30    colon  normal            anti-PD-1
32  GSM6213988    303     P30    colon   tumor            untreated
33  GSM6213989    311     P31    colon   tumor            anti-PD-1
34  GSM6213990    312     P31    colon  normal            anti-PD-1
35  GSM6213991    313     P31    colon   tumor            untreated
36  GSM6213992    321     P32    colon   tumor  Anti-PD-1+celecoxib
37  GSM6213993    322     P32    colon  normal  Anti-PD-1+celecoxib
38  GSM6213994    323     P32    colon   tumor            untreated
39  GSM6213995    333     P33   rectum   tumor            untreated

In [57]:
mtxfiles = ! ls ../../../Data/Revision/CRC_Outcome/Idvfiles/*_matrix.mtx.gz
adatas = []
for fn in mtxfiles:
    mat = mmread(fn)
    barcodes = pd.read_csv(fn.replace('matrix.mtx', 'barcodes.tsv'), sep='\t', header=None)
    features = pd.read_csv(fn.replace('matrix.mtx', 'features.tsv'), sep='\t', header=None)
    features.columns=['Ensemble', 'Gene_Symbol', 'feature_types']
    features.index = features['Ensemble'].values
    barcodes['file'] = fn
    barcodes['GSM'] = fn.split('/')[-1].split('_')[0]
    barcodes['MGI'] = fn.split('/')[-1].split('_')[2]=='MGI'
    barcodes['sample'] = fn.split('/')[-1].replace('_MGI', '').split('_')[2]
    barcodes['version'] = fn.split('/')[-1].replace('_MGI', '').split('_')[3]
    barcodes.index = barcodes['sample'] + '_' + barcodes[0]
    adata = sc.AnnData(mat.T, obs=barcodes, var=features)
    adatas.append(adata)

In [58]:
adata = anndata.concat(adatas)

In [73]:
merged = pd.merge(left=adata.obs, right=sample_info.drop('GSM', axis=1), on='sample', how='left')
(adata.obs[0] == merged[0].values).value_counts()

0
True    324020
Name: count, dtype: int64

In [76]:
merged.index = adata.obs.index
adata.obs = merged

Empty DataFrame
Columns: []
Index: [ENSG00000243485, ENSG00000237613, ENSG00000186092, ENSG00000238009, ENSG00000239945, ENSG00000239906, ENSG00000241599, ENSG00000236601, ENSG00000284733, ENSG00000235146, ENSG00000284662, ENSG00000229905, ENSG00000237491, ENSG00000177757, ENSG00000225880, ENSG00000230368, ENSG00000272438, ENSG00000230699, ENSG00000241180, ENSG00000223764, ENSG00000187634, ENSG00000188976, ENSG00000187961, ENSG00000187583, ENSG00000187642, ENSG00000272512, ENSG00000188290, ENSG00000187608, ENSG00000224969, ENSG00000188157, ENSG00000273443, ENSG00000237330, ENSG00000131591, ENSG00000223823, ENSG00000272141, ENSG00000205231, ENSG00000162571, ENSG00000186891, ENSG00000186827, ENSG00000078808, ENSG00000176022, ENSG00000184163, ENSG00000260179, ENSG00000160087, ENSG00000230415, ENSG00000162572, ENSG00000131584, ENSG00000169972, ENSG00000127054, ENSG00000224051, ENSG00000169962, ENSG00000107404, ENSG00000162576, ENSG00000175756, ENSG00000221978, ENSG00000242485, ENSG00000272455, ENSG00000235098, ENSG00000225905, ENSG00000205116, ENSG00000225285, ENSG00000179403, ENSG00000215915, ENSG00000160072, ENSG00000197785, ENSG00000205090, ENSG00000160075, ENSG00000215014, ENSG00000228594, ENSG00000272106, ENSG00000197530, ENSG00000189409, ENSG00000248333, ENSG00000272004, ENSG00000189339, ENSG00000008128, ENSG00000215790, ENSG00000008130, ENSG00000078369, ENSG00000231050, ENSG00000169885, ENSG00000178821, ENSG00000142609, ENSG00000233542, ENSG00000187730, ENSG00000226969, ENSG00000067606, ENSG00000271806, ENSG00000182873, ENSG00000162585, ENSG00000234396, ENSG00000157933, ENSG00000116151, ENSG00000157916, ENSG00000157911, ENSG00000149527, ENSG00000224387, ENSG00000229393, ENSG00000157881, ENSG00000197921, ...]

[33538 rows x 0 columns]

In [97]:
dat = pd.ExcelFile('../../../Data/Revision/CRC_Outcome/mmc2.xlsx').parse(skiprows=1)
dat = dat.rename(columns={'Tumor':'Tumor_Pre', 'Unnamed: 9':'Tumor_Post', 'Treatment response#':'response'})
dat = dat.drop(0, axis=0)
dat.index = dat['Patient ID']
dat = dat.drop('Treatment', axis=1)
dat = dat.loc[~dat['Patient ID'].isnull(), :]
adata.obs = pd.merge(left=adata.obs, right=dat.drop('Patient ID', axis=1), left_on='Patient', right_index=True, how='left')

In [103]:
adata.obs = adata.obs.drop(0, axis=1)

In [111]:
adata.var = adatas[0].var.loc[adata.var.index, :]

In [122]:
adata.var.index = adata.var['Gene_Symbol'].astype(str).values

In [123]:
adata.var_names_make_unique()

In [124]:
adata.write('../../../Data/Revision/CRC_Outcome/GSE205506_combined_counts.h5ad')